version: "3.7"
services:

  nginx:
    hostname: nginx.docker
    container_name: ${PROJECT_NAME:-demo}_nginx
    image: library/nginx:1.19.6
    restart: always
    volumes:
      - ./src:/var/www/html
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./log/nginx:/var/log/nginx
    networks:
      - backend
    depends_on:
      - php
      - mariadb
    environment:
      TZ: Europe/Prague
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    ports:
      - ${PORT_WEB:-80}:80

  php:
    hostname: php.docker
    container_name: ${PROJECT_NAME:-demo}_php
    image: library/php:7.4.15-fpm
    restart: always
    networks:
      - backend
    depends_on:
      - mariadb
    environment:
      TZ: Europe/Prague
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    volumes:
      - ./src:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./log/php:/var/log/php

  mariadb:
    hostname: mariadb.docker
    container_name: ${PROJECT_NAME:-demo}_mariadb
    image: library/mariadb:10.5.8
    restart: always
    networks:
      - backend
    env_file:
      - ./.docker/mariadb/.env
    volumes:
      - ./log/mysql:/var/log/mysql
      - .docker/mariadb/data:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: 500m
    ports:
      - ${PORT_DB:-3306}:3306

  mailhog:
    hostname: mailhog.docker
    image: mailhog/mailhog:v1.0.1
    container_name: demo_mailhog
    restart: always
    depends_on:
      - php
    networks:
      - backend
    ports:
      - ${PORT_MAILHOG:-8025}:8025

networks:
  backend:
    driver: "bridge"